apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pfnbxgs7t-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:dbc98d5cd42e75a02c5ddf4f05da1d46f2aa4013@sha256:29188f4781d11c7e116f84a18baa72ecde245ad5f9539bf436f9c723c0e0ae3c
          name: container-image
